---
- name: remove
  become: true
  become_user: root
  shell: rm -rf /usr/rc_signal || mkdir -p /usr/rc_signal/

- name: make
  become: true
  become_user: root
  shell: mkdir -p /usr/rc_signal/

- name: Copy archives
  become: true
  become_user: root
  copy:
    src: /tmp/rc_signal_tar/rc_signal.tar
    dest: /usr/rc_signal/rc_signal.tar
    force: yes

- name: Unarchive
  become: true
  become_user: root
  shell: tar -Pzxvf /usr/rc_signal/rc_signal.tar -C /usr/rc_signal/

- name: Stop
  become: true
  become_user: root
  shell: "docker stop rc_signal"
  ignore_errors: yes

- name: Remove
  become: true
  become_user: root
  shell: "docker rm rc_signal"
  ignore_errors: yes

- name: Docker build
  become: true
  become_user: root
  shell: "docker load < /usr/rc_signal/rc_signal.c.tar"

- name: Copy run script
  become: true
  become_user: root
  copy:
    src: scripts/run.sh
    mode: 0700
    dest: /tmp
    force: yes

- name: run
  become: true
  become_user: root
  no_log: true
  shell: "export POSTGRES_PASSWORD='{{pg_pw}}'; /tmp/run.sh"

