---
- name: remove
  become: true
  become_user: root
  shell: rm -rf /usr/rc_server | mkdir -p /usr/rc_server/

- name: make
  become: true
  become_user: root
  shell: mkdir -p /usr/rc_server/

- name: Copy archives
  become: true
  become_user: root
  copy:
    src: /tmp/rc_server_tar/rc_server.tar
    dest: /usr/rc_server/rc_server.tar
    force: yes

- name: Unarchive
  become: true
  become_user: root
  shell: tar -Pzxvf /usr/rc_server/rc_server.tar -C /usr/rc_server/

- name: Stop
  become: true
  become_user: root
  shell: "docker stop rc_server"
  ignore_errors: yes

- name: Remove
  become: true
  become_user: root
  shell: "docker rm rc_server"
  ignore_errors: yes

- name: Docker build
  become: true
  become_user: root
  shell: "docker load < /usr/rc_server/rc_server.c.tar"

- name: Copy run script
  become: true
  become_user: root
  copy:
    src: scripts/run.sh
    mode: 0700
    dest: /tmp
    force: yes

- name: run
  become: true
  become_user: root
  shell: "export POSTGRES_PASSWORD='{{pg_pw}}'; /tmp/run.sh"


