// APP
export const SET_APP_DIMENSIONS = 'SET_APP_DIMENSIONS';
export const CONSTRUCTING_SOCKET_REQUEST = 'CONSTRUCTING_SOCKET_REQUEST';
export const CONSTRUCTING_SOCKET_SUCCESSFULL = 'CONSTRUCTING_SOCKET_SUCCESSFULL';
export const CONSTRUCTING_SOCKET_FAIL = 'CONSTRUCTING_SOCKET_FAIL';

export const SOCKET_DATA = 'SOCKET_DATA';
